{
  "uid" : "366c1c8076b602f4",
  "name" : "两次密码不一致",
  "fullName" : "testcases.test_my_interface01.test_register.TestRegister#test_register",
  "historyId" : "dd9414f4b8580038314f88520733efbe",
  "time" : {
    "start" : 1646221621820,
    "stop" : 1646221621854,
    "duration" : 34
  },
  "description" : "京东小程序入口注册接口",
  "descriptionHtml" : "<p>京东小程序入口注册接口</p>\n",
  "status" : "passed",
  "flaky" : false,
  "newFailed" : false,
  "newBroken" : false,
  "newPassed" : false,
  "retriesCount" : 9,
  "retriesStatusChange" : true,
  "beforeStages" : [ {
    "name" : "connect_db",
    "time" : {
      "start" : 1646221621817,
      "stop" : 1646221621820,
      "duration" : 3
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  } ],
  "testStage" : {
    "description" : "京东小程序入口注册接口",
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "55d5bcedca91b046",
      "name" : "接口路径",
      "source" : "55d5bcedca91b046.attach",
      "type" : "text/plain",
      "size" : 30
    }, {
      "uid" : "e1cfcb22b5159827",
      "name" : "接口参数",
      "source" : "e1cfcb22b5159827.attach",
      "type" : "text/plain",
      "size" : 116
    }, {
      "uid" : "d44469309751ff99",
      "name" : "响应结果",
      "source" : "d44469309751ff99.attach",
      "type" : "text/plain",
      "size" : 52
    }, {
      "uid" : "aee427a013cf3992",
      "name" : "log",
      "source" : "aee427a013cf3992.txt",
      "type" : "text/plain",
      "size" : 315
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : true,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 4
  },
  "afterStages" : [ {
    "name" : "connect_db::0",
    "time" : {
      "start" : 1646221621855,
      "stop" : 1646221621855,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  } ],
  "labels" : [ {
    "name" : "severity",
    "value" : "critical"
  }, {
    "name" : "feature",
    "value" : "注册模块"
  }, {
    "name" : "parentSuite",
    "value" : "testcases.test_my_interface01"
  }, {
    "name" : "suite",
    "value" : "test_register"
  }, {
    "name" : "subSuite",
    "value" : "TestRegister"
  }, {
    "name" : "host",
    "value" : "DESKTOP-364LE5K"
  }, {
    "name" : "thread",
    "value" : "3476-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "testcases.test_my_interface01.test_register"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "case",
    "value" : "<comms.excel_utils.CaseData object at 0x0000026CA1F59BA8>"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "critical",
    "retries" : [ {
      "uid" : "7b402715f14f91dc",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /register (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015522A52978>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1646221558468,
        "stop" : 1646221560503,
        "duration" : 2035
      }
    }, {
      "uid" : "284992a65bedc438",
      "status" : "passed",
      "time" : {
        "start" : 1646199361004,
        "stop" : 1646199361032,
        "duration" : 28
      }
    }, {
      "uid" : "f9310dbce3cebce0",
      "status" : "broken",
      "statusDetails" : "PermissionError: [Errno 13] Permission denied: 'D:\\\\PythonWorkSpace\\\\autotest\\\\datas\\\\cases.xlsx'",
      "time" : {
        "start" : 1646199309416,
        "stop" : 1646199309430,
        "duration" : 14
      }
    }, {
      "uid" : "640d2c6d0426936",
      "status" : "broken",
      "statusDetails" : "PermissionError: [Errno 13] Permission denied: 'D:\\\\PythonWorkSpace\\\\autotest\\\\datas\\\\cases.xlsx'",
      "time" : {
        "start" : 1646199217136,
        "stop" : 1646199217150,
        "duration" : 14
      }
    }, {
      "uid" : "f9449ee0b1ced924",
      "status" : "broken",
      "statusDetails" : "PermissionError: [Errno 13] Permission denied: 'D:\\\\PythonWorkSpace\\\\autotest\\\\datas\\\\cases.xlsx'",
      "time" : {
        "start" : 1646199158937,
        "stop" : 1646199158950,
        "duration" : 13
      }
    }, {
      "uid" : "801666faf9e1f9b9",
      "status" : "broken",
      "statusDetails" : "PermissionError: [Errno 13] Permission denied: 'D:\\\\PythonWorkSpace\\\\autotest\\\\datas\\\\cases.xlsx'",
      "time" : {
        "start" : 1646198939845,
        "stop" : 1646198939858,
        "duration" : 13
      }
    }, {
      "uid" : "bb287ec588ffc2e6",
      "status" : "passed",
      "time" : {
        "start" : 1646198591052,
        "stop" : 1646198591080,
        "duration" : 28
      }
    }, {
      "uid" : "287d769825149649",
      "status" : "passed",
      "time" : {
        "start" : 1646198233955,
        "stop" : 1646198233981,
        "duration" : 26
      }
    }, {
      "uid" : "18babe38464e9660",
      "status" : "broken",
      "statusDetails" : "FileNotFoundError: [Errno 2] No such file or directory: '../test_excel_data03/cases.xlsx'",
      "time" : {
        "start" : 1646198019878,
        "stop" : 1646198019884,
        "duration" : 6
      }
    } ],
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "366c1c8076b602f4.json",
  "parameterValues" : [ "<comms.excel_utils.CaseData object at 0x0000026CA1F59BA8>" ]
}