{
  "uid" : "7779aba54f5ce1fb",
  "name" : "手机号码为空",
  "fullName" : "testcases.test_my_interface01.test_register.TestRegister#test_register",
  "historyId" : "a66a1294c3efdc4645cb1c6bf3c6092a",
  "time" : {
    "start" : 1646221621903,
    "stop" : 1646221621940,
    "duration" : 37
  },
  "description" : "京东小程序入口注册接口",
  "descriptionHtml" : "<p>京东小程序入口注册接口</p>\n",
  "status" : "passed",
  "flaky" : false,
  "newFailed" : false,
  "newBroken" : false,
  "newPassed" : false,
  "retriesCount" : 9,
  "retriesStatusChange" : true,
  "beforeStages" : [ {
    "name" : "connect_db",
    "time" : {
      "start" : 1646221621899,
      "stop" : 1646221621902,
      "duration" : 3
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  } ],
  "testStage" : {
    "description" : "京东小程序入口注册接口",
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "94cac793a0018070",
      "name" : "接口路径",
      "source" : "94cac793a0018070.attach",
      "type" : "text/plain",
      "size" : 30
    }, {
      "uid" : "fa2e4e1ee8e98095",
      "name" : "接口参数",
      "source" : "fa2e4e1ee8e98095.attach",
      "type" : "text/plain",
      "size" : 104
    }, {
      "uid" : "76dc7df8237c409f",
      "name" : "响应结果",
      "source" : "76dc7df8237c409f.attach",
      "type" : "text/plain",
      "size" : 46
    }, {
      "uid" : "a659a61b67a54798",
      "name" : "log",
      "source" : "a659a61b67a54798.txt",
      "type" : "text/plain",
      "size" : 312
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : true,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 4
  },
  "afterStages" : [ {
    "name" : "connect_db::0",
    "time" : {
      "start" : 1646221621941,
      "stop" : 1646221621941,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  } ],
  "labels" : [ {
    "name" : "severity",
    "value" : "critical"
  }, {
    "name" : "feature",
    "value" : "注册模块"
  }, {
    "name" : "parentSuite",
    "value" : "testcases.test_my_interface01"
  }, {
    "name" : "suite",
    "value" : "test_register"
  }, {
    "name" : "subSuite",
    "value" : "TestRegister"
  }, {
    "name" : "host",
    "value" : "DESKTOP-364LE5K"
  }, {
    "name" : "thread",
    "value" : "3476-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "testcases.test_my_interface01.test_register"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "case",
    "value" : "<comms.excel_utils.CaseData object at 0x0000026CA1F59B00>"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "critical",
    "retries" : [ {
      "uid" : "70d0f461ba67649",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /register (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015522BFF0F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1646221562898,
        "stop" : 1646221564931,
        "duration" : 2033
      }
    }, {
      "uid" : "892771b2368709d4",
      "status" : "passed",
      "time" : {
        "start" : 1646199361075,
        "stop" : 1646199361102,
        "duration" : 27
      }
    }, {
      "uid" : "d84cef0b262e7a96",
      "status" : "broken",
      "statusDetails" : "PermissionError: [Errno 13] Permission denied: 'D:\\\\PythonWorkSpace\\\\autotest\\\\datas\\\\cases.xlsx'",
      "time" : {
        "start" : 1646199309583,
        "stop" : 1646199309597,
        "duration" : 14
      }
    }, {
      "uid" : "987c082d92d9d2c4",
      "status" : "broken",
      "statusDetails" : "PermissionError: [Errno 13] Permission denied: 'D:\\\\PythonWorkSpace\\\\autotest\\\\datas\\\\cases.xlsx'",
      "time" : {
        "start" : 1646199217290,
        "stop" : 1646199217305,
        "duration" : 15
      }
    }, {
      "uid" : "9b4a583f20974e42",
      "status" : "broken",
      "statusDetails" : "PermissionError: [Errno 13] Permission denied: 'D:\\\\PythonWorkSpace\\\\autotest\\\\datas\\\\cases.xlsx'",
      "time" : {
        "start" : 1646199159102,
        "stop" : 1646199159142,
        "duration" : 40
      }
    }, {
      "uid" : "4e643bcb46148ddf",
      "status" : "broken",
      "statusDetails" : "PermissionError: [Errno 13] Permission denied: 'D:\\\\PythonWorkSpace\\\\autotest\\\\datas\\\\cases.xlsx'",
      "time" : {
        "start" : 1646198940000,
        "stop" : 1646198940015,
        "duration" : 15
      }
    }, {
      "uid" : "785a23bd71ca2941",
      "status" : "passed",
      "time" : {
        "start" : 1646198591119,
        "stop" : 1646198591146,
        "duration" : 27
      }
    }, {
      "uid" : "66163d72dc76b612",
      "status" : "passed",
      "time" : {
        "start" : 1646198234021,
        "stop" : 1646198234052,
        "duration" : 31
      }
    }, {
      "uid" : "95064646214c4ef1",
      "status" : "broken",
      "statusDetails" : "FileNotFoundError: [Errno 2] No such file or directory: '../test_excel_data03/cases.xlsx'",
      "time" : {
        "start" : 1646198020019,
        "stop" : 1646198020025,
        "duration" : 6
      }
    } ],
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "7779aba54f5ce1fb.json",
  "parameterValues" : [ "<comms.excel_utils.CaseData object at 0x0000026CA1F59B00>" ]
}