{
  "uid" : "83e4a447ee74735e",
  "name" : "正常流程",
  "fullName" : "testcases.test_my_interface01.test_login.TestLogin#test_login",
  "historyId" : "0c53c865c10cd0d13c63cf2a4416cadc",
  "time" : {
    "start" : 1646221621531,
    "stop" : 1646221621573,
    "duration" : 42
  },
  "description" : "京东小程序入口登入接口",
  "descriptionHtml" : "<p>京东小程序入口登入接口</p>\n",
  "status" : "passed",
  "flaky" : false,
  "newFailed" : false,
  "newBroken" : false,
  "newPassed" : false,
  "retriesCount" : 12,
  "retriesStatusChange" : true,
  "beforeStages" : [ ],
  "testStage" : {
    "description" : "京东小程序入口登入接口",
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "6ccdc5cb80d2bda1",
      "name" : "接口路径",
      "source" : "6ccdc5cb80d2bda1.attach",
      "type" : "text/plain",
      "size" : 32
    }, {
      "uid" : "da854fe3e6028214",
      "name" : "接口参数",
      "source" : "da854fe3e6028214.attach",
      "type" : "text/plain",
      "size" : 47
    }, {
      "uid" : "a80437327e5c5d01",
      "name" : "响应结果",
      "source" : "a80437327e5c5d01.attach",
      "type" : "text/plain",
      "size" : 37
    }, {
      "uid" : "6de330334f00248c",
      "name" : "log",
      "source" : "6de330334f00248c.txt",
      "type" : "text/plain",
      "size" : 305
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : true,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 4
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "severity",
    "value" : "critical"
  }, {
    "name" : "feature",
    "value" : "登入模块"
  }, {
    "name" : "parentSuite",
    "value" : "testcases.test_my_interface01"
  }, {
    "name" : "suite",
    "value" : "test_login"
  }, {
    "name" : "subSuite",
    "value" : "TestLogin"
  }, {
    "name" : "host",
    "value" : "DESKTOP-364LE5K"
  }, {
    "name" : "thread",
    "value" : "3476-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "testcases.test_my_interface01.test_login"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "case",
    "value" : "<comms.excel_utils.CaseData object at 0x0000026CA1F0A128>"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "critical",
    "retries" : [ {
      "uid" : "1c72a9dc6cb6ee0a",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /user_login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002C0ABA2D390>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1646221591325,
        "stop" : 1646221593355,
        "duration" : 2030
      }
    }, {
      "uid" : "c0376711bbfdef87",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /user_login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000155227DF748>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1646221542928,
        "stop" : 1646221544958,
        "duration" : 2030
      }
    }, {
      "uid" : "26923f81a2a81d68",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /user_login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DD0F83B4E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1646221486646,
        "stop" : 1646221488672,
        "duration" : 2026
      }
    }, {
      "uid" : "c8224ac6d140e685",
      "status" : "passed",
      "time" : {
        "start" : 1646199360739,
        "stop" : 1646199360782,
        "duration" : 43
      }
    }, {
      "uid" : "9edc97163b5117b7",
      "status" : "broken",
      "statusDetails" : "PermissionError: [Errno 13] Permission denied: 'D:\\\\PythonWorkSpace\\\\autotest\\\\datas\\\\cases.xlsx'",
      "time" : {
        "start" : 1646199308763,
        "stop" : 1646199308789,
        "duration" : 26
      }
    }, {
      "uid" : "c43e8a550d1a52c7",
      "status" : "broken",
      "statusDetails" : "PermissionError: [Errno 13] Permission denied: 'D:\\\\PythonWorkSpace\\\\autotest\\\\datas\\\\cases.xlsx'",
      "time" : {
        "start" : 1646199215973,
        "stop" : 1646199216540,
        "duration" : 567
      }
    }, {
      "uid" : "9b637a830a1dfedf",
      "status" : "broken",
      "statusDetails" : "PermissionError: [Errno 13] Permission denied: 'D:\\\\PythonWorkSpace\\\\autotest\\\\datas\\\\cases.xlsx'",
      "time" : {
        "start" : 1646199158311,
        "stop" : 1646199158338,
        "duration" : 27
      }
    }, {
      "uid" : "432594c843604795",
      "status" : "broken",
      "statusDetails" : "PermissionError: [Errno 13] Permission denied: 'D:\\\\PythonWorkSpace\\\\autotest\\\\datas\\\\cases.xlsx'",
      "time" : {
        "start" : 1646198939224,
        "stop" : 1646198939250,
        "duration" : 26
      }
    }, {
      "uid" : "96fcebb983d26034",
      "status" : "passed",
      "time" : {
        "start" : 1646198590696,
        "stop" : 1646198590744,
        "duration" : 48
      }
    }, {
      "uid" : "109c2e4b58be7b9a",
      "status" : "passed",
      "time" : {
        "start" : 1646198233598,
        "stop" : 1646198233647,
        "duration" : 49
      }
    }, {
      "uid" : "811ad7e6bca11ee1",
      "status" : "broken",
      "statusDetails" : "FileNotFoundError: [Errno 2] No such file or directory: '../test_excel_data03/cases.xlsx'",
      "time" : {
        "start" : 1646198019310,
        "stop" : 1646198019328,
        "duration" : 18
      }
    }, {
      "uid" : "b3a16c6463fe1142",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /user_login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000200FFEAB5C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1646197953993,
        "stop" : 1646197956044,
        "duration" : 2051
      }
    } ],
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "83e4a447ee74735e.json",
  "parameterValues" : [ "<comms.excel_utils.CaseData object at 0x0000026CA1F0A128>" ]
}