{
  "uid" : "e0afa70b77727be",
  "name" : "邮箱为空",
  "fullName" : "testcases.test_my_interface01.test_register.TestRegister#test_register",
  "historyId" : "745a8babde3b2836921035ab79c783d4",
  "time" : {
    "start" : 1646221621862,
    "stop" : 1646221621896,
    "duration" : 34
  },
  "description" : "京东小程序入口注册接口",
  "descriptionHtml" : "<p>京东小程序入口注册接口</p>\n",
  "status" : "passed",
  "flaky" : false,
  "newFailed" : false,
  "newBroken" : false,
  "newPassed" : false,
  "retriesCount" : 9,
  "retriesStatusChange" : true,
  "beforeStages" : [ {
    "name" : "connect_db",
    "time" : {
      "start" : 1646221621858,
      "stop" : 1646221621861,
      "duration" : 3
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  } ],
  "testStage" : {
    "description" : "京东小程序入口注册接口",
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "46975d45c5f8a536",
      "name" : "接口路径",
      "source" : "46975d45c5f8a536.attach",
      "type" : "text/plain",
      "size" : 30
    }, {
      "uid" : "74b9fec8a3df5f2a",
      "name" : "接口参数",
      "source" : "74b9fec8a3df5f2a.attach",
      "type" : "text/plain",
      "size" : 104
    }, {
      "uid" : "6d873c7e9f6437b6",
      "name" : "响应结果",
      "source" : "6d873c7e9f6437b6.attach",
      "type" : "text/plain",
      "size" : 43
    }, {
      "uid" : "a31aa01034086080",
      "name" : "log",
      "source" : "a31aa01034086080.txt",
      "type" : "text/plain",
      "size" : 306
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : true,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 4
  },
  "afterStages" : [ {
    "name" : "connect_db::0",
    "time" : {
      "start" : 1646221621897,
      "stop" : 1646221621897,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  } ],
  "labels" : [ {
    "name" : "severity",
    "value" : "critical"
  }, {
    "name" : "feature",
    "value" : "注册模块"
  }, {
    "name" : "parentSuite",
    "value" : "testcases.test_my_interface01"
  }, {
    "name" : "suite",
    "value" : "test_register"
  }, {
    "name" : "subSuite",
    "value" : "TestRegister"
  }, {
    "name" : "host",
    "value" : "DESKTOP-364LE5K"
  }, {
    "name" : "thread",
    "value" : "3476-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "testcases.test_my_interface01.test_register"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "case",
    "value" : "<comms.excel_utils.CaseData object at 0x0000026CA1F59438>"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "critical",
    "retries" : [ {
      "uid" : "bfdcc9cf1b68d4a1",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /register (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015522935BA8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1646221560692,
        "stop" : 1646221562723,
        "duration" : 2031
      }
    }, {
      "uid" : "24894b2ff6abbc56",
      "status" : "passed",
      "time" : {
        "start" : 1646199361040,
        "stop" : 1646199361068,
        "duration" : 28
      }
    }, {
      "uid" : "a5410cbbed392ac9",
      "status" : "broken",
      "statusDetails" : "PermissionError: [Errno 13] Permission denied: 'D:\\\\PythonWorkSpace\\\\autotest\\\\datas\\\\cases.xlsx'",
      "time" : {
        "start" : 1646199309506,
        "stop" : 1646199309522,
        "duration" : 16
      }
    }, {
      "uid" : "be2f8f687d642b4f",
      "status" : "broken",
      "statusDetails" : "PermissionError: [Errno 13] Permission denied: 'D:\\\\PythonWorkSpace\\\\autotest\\\\datas\\\\cases.xlsx'",
      "time" : {
        "start" : 1646199217218,
        "stop" : 1646199217232,
        "duration" : 14
      }
    }, {
      "uid" : "c8bee5d3fc0b0626",
      "status" : "broken",
      "statusDetails" : "PermissionError: [Errno 13] Permission denied: 'D:\\\\PythonWorkSpace\\\\autotest\\\\datas\\\\cases.xlsx'",
      "time" : {
        "start" : 1646199159019,
        "stop" : 1646199159033,
        "duration" : 14
      }
    }, {
      "uid" : "737f9c83eaf4a08e",
      "status" : "broken",
      "statusDetails" : "PermissionError: [Errno 13] Permission denied: 'D:\\\\PythonWorkSpace\\\\autotest\\\\datas\\\\cases.xlsx'",
      "time" : {
        "start" : 1646198939927,
        "stop" : 1646198939941,
        "duration" : 14
      }
    }, {
      "uid" : "f5813c168966bd04",
      "status" : "passed",
      "time" : {
        "start" : 1646198591086,
        "stop" : 1646198591113,
        "duration" : 27
      }
    }, {
      "uid" : "e99ed45b3902919b",
      "status" : "passed",
      "time" : {
        "start" : 1646198233988,
        "stop" : 1646198234015,
        "duration" : 27
      }
    }, {
      "uid" : "5067d7ba342f177c",
      "status" : "broken",
      "statusDetails" : "FileNotFoundError: [Errno 2] No such file or directory: '../test_excel_data03/cases.xlsx'",
      "time" : {
        "start" : 1646198019942,
        "stop" : 1646198019947,
        "duration" : 5
      }
    } ],
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "e0afa70b77727be.json",
  "parameterValues" : [ "<comms.excel_utils.CaseData object at 0x0000026CA1F59438>" ]
}